name: fokuskripto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  dropdown_search: ^5.0.2
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  fl_chart: ^0.68.0
  sensors_plus: ^3.0.0
  local_auth: ^2.1.8
  firebase_messaging: ^14.7.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/kriptoin.png
    - assets/logo/rupiah.png
  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/kriptoin.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/kriptoin.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo/kriptoin.png"
  android: true
